version: '2'
services:
  wso2ei-mysql:
    image: mysql:5.7.20
    container_name: wso2ei-mysql
    hostname: wso2ei-mysql
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      # mounting MySQL init scripts
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      # mounting MySQL DB data
      - ./mysql/data:/var/lib/mysql
  wso2ei-analytics:
    image: wso2ei-analytics:6.1.1
    container_name: wso2ei-analytics
    hostname: wso2ei-analytics
    ports:
      - 9444:9444
      - 9612:9612
      - 9712:9712
      - 7712:7712
      - 7612:7612
    volumes:
      # mounting configurations
      - ./analytics/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/conf/datasources/master-datasources.xml
      - ./analytics/conf/registry.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/conf/registry.xml
      - ./analytics/conf/user-mgt.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/conf/user-mgt.xml
      - ./analytics/conf/carbon.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/conf/carbon.xml
      - ./analytics/conf/datasources/analytics-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/conf/datasources/analytics-datasources.xml
      # mounting keystores
      - ./analytics/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/repository/resources/security/wso2carbon.jks
      - ./analytics/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/analytics/repository/resources/security/client-truststore.jks
    depends_on:
      - wso2ei-mysql
    links:
      - wso2ei-mysql
  wso2ei-business-process:
    image: wso2ei-business-process:6.1.1
    container_name: wso2ei-business-process
    hostname: wso2ei-business-process
    ports:
      - 9445:9445
    volumes:
      # mounting configurations
      - ./business-process/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/datasources/master-datasources.xml
      - ./business-process/conf/datasources/bps-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/datasources/bps-datasources.xml
      - ./business-process/conf/datasources/activiti-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/datasources/activiti-datasources.xml
      - ./business-process/conf/etc/tasks-config.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/etc/tasks-config.xml
      - ./business-process/conf/registry.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/registry.xml
      - ./business-process/conf/user-mgt.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/user-mgt.xml
      - ./business-process/conf/bps.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/bps.xml
      - ./business-process/conf/carbon.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/conf/carbon.xml
      # mounting keystores
      - ./business-process/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/repository/resources/security/wso2carbon.jks
      - ./business-process/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/business-process/repository/resources/security/client-truststore.jks
    depends_on:
      - wso2ei-mysql
      - wso2ei-analytics
    links:
      - wso2ei-mysql
      - wso2ei-analytics
  wso2ei-broker:
    image: wso2ei-broker:6.1.1
    container_name: wso2ei-broker
    hostname: wso2ei-broker
    ports:
      - 9446:9446
      - 5675:5675
      - 8675:8675
      - 1886:1886
      - 8836:8836
      - 7614:7614
    volumes:
      # mounting configurations
      - ./broker/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/conf/datasources/master-datasources.xml
      - ./broker/conf/registry.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/conf/registry.xml
      - ./broker/conf/user-mgt.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/conf/user-mgt.xml
      - ./broker/conf/broker.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/conf/broker.xml
      - ./broker/conf/carbon.xml:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/conf/carbon.xml
      # mounting keystores
      - ./broker/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/repository/resources/security/wso2carbon.jks
      - ./broker/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2ei-6.1.1/wso2/broker/repository/resources/security/client-truststore.jks
    depends_on:
      - wso2ei-mysql
      - wso2ei-analytics
      - wso2ei-business-process
    links:
      - wso2ei-mysql
      - wso2ei-analytics
      - wso2ei-business-process
  wso2ei-integrator:
    image: wso2ei-integrator:6.1.1
    container_name: wso2ei-integrator
    hostname: wso2ei-integrator
    ports:
      - 9443:9443
      - 8243:8243
      - 8280:8280
    volumes:
      # mounting configurations
      - ./integrator/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2ei-6.1.1/conf/datasources/master-datasources.xml
      - ./integrator/conf/user-mgt.xml:/home/wso2carbon/wso2ei-6.1.1/conf/user-mgt.xml
      - ./integrator/conf/registry.xml:/home/wso2carbon/wso2ei-6.1.1/conf/registry.xml
      - ./integrator/conf/synapse.properties:/home/wso2carbon/wso2ei-6.1.1/conf/synapse.properties
      - ./integrator/conf/jndi.properties:/home/wso2carbon/wso2ei-6.1.1/conf/jndi.properties
      - ./integrator/conf/carbon.xml:/home/wso2carbon/wso2ei-6.1.1/conf/carbon.xml
      - ./integrator/conf/axis2/axis2.xml:/home/wso2carbon/wso2ei-6.1.1/conf/axis2/axis2.xml
      # mounting carbon apps
      - ./integrator/repository/deployment/server/carbonapps:/home/wso2carbon/wso2ei-6.1.1/repository/deployment/server/carbonapps
      # mounting analytics event publishers
      - ./integrator/repository/deployment/server/eventpublishers:/home/wso2carbon/wso2ei-6.1.1/repository/deployment/server/eventpublishers
      # mounting synapse artifacts
      - ./integrator/repository/deployment/server/synapse-configs:/home/wso2carbon/wso2ei-6.1.1/repository/deployment/server/synapse-configs
      # mounting keystores
      - ./integrator/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2ei-6.1.1/epository/resources/security/wso2carbon.jks
      - ./integrator/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2ei-6.1.1/repository/resources/security/client-truststore.jks
    depends_on:
      - wso2ei-mysql
      - wso2ei-analytics
      - wso2ei-business-process
      - wso2ei-broker
    links:
      - wso2ei-mysql
      - wso2ei-analytics
      - wso2ei-business-process
      - wso2ei-broker
